name: dependency_initializer
description: Initializer utility of dependencies for Dart & Flutter projects.
version: 1.0.2
repository: https://github.com/ivangalkindeveloper/dependency_initializer

topics:
  - dart
  - dependency
  - dependencies
  - utility
  - utils

environment:
  sdk: ^3.4.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
