name: initializer
description: Initializer utility for resources of Dart & Flutter projects.
version: 1.0.0
repository: https://github.com/ivangalkindeveloper/initializer

topics:
  - dart
  - utility
  - utils

environment:
  sdk: ^3.4.3

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
